albac/albac.dev

amplify/backend/auth/albacdev9c9c3dfe/cli-inputs.json
=> Revert "save changes"

amplify/backend/auth/albacdev9c9c3dfe/cli-inputs.json
=> Revert "changes for prod"

next-env.d.ts, pages/_app.tsx, tsconfig.json
This should be the minimum change we can do to enable typescript on the project.
=> Adding support for typescript

package-lock.json, package.json, yarn.lock
These missing modules are needed for amplify
=> adding missing modules

pages/storagemanager.tsx
Following this instructions for data storage management:
https://aws.amazon.com/blogs/mobile/announcing-the-amplify-ui-storagemanager-component/
=> Storage Page component

components/BlogListItem.js, pages/projects.js
=> Cambios de estilos en la Página Projects

amplify/backend/backend-config.json, amplify/backend/storage/blogimages/cli-inputs.json
=> Permission added for groups 2

components/BlogListItem.js
1- changed the styles in light mode
=> changed the styles in light mode

package-lock.json, package.json, yarn.lock
Here only making packages changes to test if amplify is working with latest version.
=> First commit, adding only packages changes

components/Navbar.js
Quick hotfix to test removing a dynamic import on mobile and h1 tag
=> Removing no needed dynamic import and h1 tag

app/storagemanager/page.tsx
Missed storage manager page, adding it so we can test this on our dev env.
=> adding storage manager page

components/AuthButton.tsx, components/Navbar.tsx
- create select
- onchange select -> redirect chagptmodel select
- onclick button signin -> close menu modal
- change name of the select, Chat-GPT -> ChatGPT
=> select navigate to chatgpt models

app/blog/[slug]/EditButton.tsx, app/blog/[slug]/MdxToHtml.tsx, app/blog/[slug]/page.tsx
- create EditButton (authStatus require "use client")
- create MdxToHtml (mdxRemote require "use client")
-  import new components in [slug].page
=> slug changes

pages/_app.tsx, pages/blog/[slug].js
- solution from styles in new slug
=> styles in new slug

app/homepage-img.tsx, app/logo-img.tsx, app/profile/image-profile.tsx, app/profile/page.tsx
- conditional not to send images without url
=> soluted images not found

mdxfiles/privacy-policy.mdx, mdxfiles/terms-conditions.mdx
=> Just updating privacy and terms

components/Navbar.tsx
This should add logo for dev to
=> Adding dev.to logo and link

components/Navbar.tsx
=> Changing to about

components/post-image.tsx, pages/blog/[slug].js
We can change the image for a specific size
=> Image from aws s3 and responsive

pages/blog/[slug].js
=> adding this to run every 5 min

app/chatgpt/[model]/layout.tsx, app/page.tsx, app/profile/page.tsx, app/projects/page.tsx
fixed an error in the "keywords" property name
=> added type Metadata, and, soluted error: keyboards -> keywords

amplify/team-provider-info.json, app/App.tsx, app/layout.tsx, components/AuthenticatorProvider.tsx, components/Footer.tsx, components/Navbar.tsx, utils/configureAmplify.ts
- Removed direct AWS Amplify configuration from `RootLayout` and `AuthenticatorProvider`, centralizing it in `utils/configureAmplify.ts`. This centralization enhances modularity and avoids code duplication.
- Updated `RootLayout` to use React Fragment and `Head` from Next.js for better SEO and code clarity. 
- Extracted the footer into a separate `Footer` component and imported it in `RootLayout`, enhancing the reusability and maintainability of the code.
- Simplified the `AuthenticatorProvider` by removing redundant Amplify configuration.
- Adjusted the `Navbar` component structure for better layout consistency.
=> Refactor layout and authentication 
